version: "3.4"

services:
  toroapplication:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:443;http://+:80
    ports:
      - "80"
      - "443"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro
  toroclientapplication:
    ports:
      - "3000:3000"
    volumes:
      - ./ToroClientApplication/toro-app/src:/clientApp/src
